/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 case.glb -k 
Author: dylanheyes (https://sketchfab.com/dylanheyes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-pc-case-5f9261fef2874bf9ae39dd0f4029e978
Title: Gaming PC Case
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Case(props) {
  const { nodes, materials } = useGLTF("./case.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        position={[0, 2, 13]}
        rotation={[-Math.PI / 2, 0.2, -0.3]}
        scale={1}
      >
        <group
          name="a4725b22ae464d0a9aa2d92dddbd4318fbx"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group name="Nightshark" scale={100}>
            <mesh
              name="Nightshark_Window_0"
              geometry={nodes.Nightshark_Window_0.geometry}
              material={materials.Window}
            />
            <mesh
              name="Nightshark_Plastics_0"
              geometry={nodes.Nightshark_Plastics_0.geometry}
              material={materials.Plastics}
            />
            <mesh
              name="Nightshark_Plastics_0_1"
              geometry={nodes.Nightshark_Plastics_0_1.geometry}
              material={materials.Plastics}
            />
            <mesh
              name="Nightshark_Plastics_0_2"
              geometry={nodes.Nightshark_Plastics_0_2.geometry}
              material={materials.Plastics}
            />
            <mesh
              name="Nightshark_Plastics_0_3"
              geometry={nodes.Nightshark_Plastics_0_3.geometry}
              material={materials.Plastics}
            />
            <mesh
              name="Nightshark_RGB_0"
              geometry={nodes.Nightshark_RGB_0.geometry}
              material={materials.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/case.glb");
